<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>MelonLoader</AssemblyName>
    <RootNamespace>MelonLoaderStubs</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>CS1591;CS0067;CS0626;CS0649;CS0414;CS8618;CS8625;CS8632;CS0436;CS0108;CS0114</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="MelonLoader.cs" />
  </ItemGroup>
</Project>
