<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>UnityEngine.UI</AssemblyName>
    <RootNamespace>UnityUiStubs</RootNamespace>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>CS1591;CS0067;CS0626;CS0649;CS0414;CS8618;CS8625;CS8632;CS0436;CS0108;CS0114</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="UnityUi.cs" />
    <Reference Include="UnityEngine">
      <HintPath>$(MSBuildProjectDirectory)/bin/Release/UnityEngine.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
