using MelonLoader;
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using TMPro;
using UnityEngine;
using UnityEngine.InputSystem;

[assembly: MelonInfo(typeof(SuperHackerGolf), "SuperHackerGolf", "1.0.0", "luinbytes")]
[assembly: MelonGame]

public partial class SuperHackerGolf : MelonMod
{
    private Component playerMovement;
    private Component playerGolfer;
    private Component golfBall;

    private readonly Dictionary<string, PropertyInfo> playerGolferProperties = new Dictionary<string, PropertyInfo>(8);
    private readonly Dictionary<string, FieldInfo> playerGolferFields = new Dictionary<string, FieldInfo>(4);

    private MethodInfo addSpeedBoostMethod;
    private FieldInfo swingNormalizedPowerBackingField;

    private bool playerFound;
    private bool assistEnabled;
    private bool isLeftMousePressed;
    private bool isRightMousePressed;
    private bool autoReleaseTriggeredThisCharge;
    private bool autoChargeSequenceStarted;
    private int lastAutoSwingReleaseFrame = -1;
    private float nextTryStartChargingTime;
    private readonly float tryStartChargingInterval = 0.05f;
    private float idealSwingPower;
    private float idealSwingPitch;
    private Vector3 flagPosition = Vector3.zero;
    private Vector3 holePosition = Vector3.zero;
    private Vector3 currentAimTargetPosition = Vector3.zero;
    private Vector3 currentSwingOriginPosition = Vector3.zero;
    private Vector3 aimTargetOffsetLocal = Vector3.zero;
    private readonly Vector3 swingOriginLocalOffset = new Vector3(0.86f, 0.05f, -0.12f);

    private string cachedLocalPlayerDisplayName = "";
    private float nextDisplayNameRefreshTime;
    private readonly float displayNameRefreshInterval = 0.5f;

    private int cachedAllGameObjectsFrame = -1;
    private GameObject[] cachedAllGameObjects;
    private int cachedAllComponentsFrame = -1;
    private Component[] cachedAllComponents;
    private float nextPlayerSearchTime;
    private float nextHoleSearchTime;
    private float nextIdealSwingCalculationTime;
    private float nextBallResolveTime;
    private readonly float playerSearchInterval = 1f;
    private readonly float holeSearchInterval = 0.5f;
    private readonly float idealSwingCalculationInterval = 0.25f;
    private readonly float ballResolveInterval = 0.2f;
    private readonly float puttDistanceThreshold = 12f;

    private bool hadResolvedPlayerContext;
    private bool hadResolvedBallContext;
    private string lastBallResolveSource = "missing";
    private Component initializedPlayerGolfer;

    private GameObject hudCanvas;
    private TextMeshProUGUI leftHudText;
    private TextMeshProUGUI centerHudText;
    private TextMeshProUGUI rightHudText;
    private TextMeshProUGUI bottomHudText;

    private bool isAimModeActive;
    private bool wasAimRequestedLastFrame;
    private bool reflectionCacheInitialized;
    private MethodInfo cachedTryGetMethod;
    private MethodInfo cachedOrbitSetYawMethod;
    private MethodInfo cachedOrbitSetPitchMethod;
    private MethodInfo cachedOrbitForceUpdateMethod;
    private MethodInfo cachedEnterSwingAimCameraMethod;
    private MethodInfo cachedExitSwingAimCameraMethod;
    private MethodInfo cachedReachOrbitSteadyStateMethod;
    private Component initializedYawPlayerMovement;
    private PropertyInfo cachedPlayerMovementYawProperty;
    private FieldInfo cachedPlayerMovementYawField;
    private Component initializedYawPlayerGolfer;
    private PropertyInfo cachedPlayerGolferYawProperty;
    private FieldInfo cachedPlayerGolferYawField;
    private bool cameraAimSmoothingInitialized;
    private float smoothedOrbitYaw;
    private float smoothedOrbitPitch;
    private float orbitYawVelocity;
    private float orbitPitchVelocity;
    private readonly float orbitAimSmoothTime = 0.02f;
    private readonly float orbitAimMaxSpeed = 2160f;
    private readonly object[] cachedOrbitModuleQueryArgs = new object[1];
    private readonly object[] cachedOrbitYawArgs = new object[1];
    private readonly object[] cachedOrbitPitchArgs = new object[1];

    private bool swingMathReflectionInitialized;
    private PropertyInfo cachedGolfSettingsProperty;
    private object cachedGolfSettingsObject;
    private PropertyInfo cachedGolfBallSettingsProperty;
    private object cachedGolfBallSettingsObject;
    private MethodInfo cachedBMathEaseInMethod;
    private MethodInfo cachedUpdateSwingNormalizedPowerMethod;
    private bool matchSetupRulesReflectionInitialized;
    private Type cachedMatchSetupRuleEnumType;
    private MethodInfo cachedMatchSetupGetValueMethod;
    private object cachedMatchSetupSwingPowerRuleValue;
    private PropertyInfo cachedLocalPlayerAsGolferProperty;
    private bool localGolferResolverInitialized;
    private MethodInfo cachedTryStartChargingSwingMethod;
    private MethodInfo cachedSetIsChargingSwingMethod;
    private MethodInfo cachedReleaseSwingChargeMethod;
    private float lastObservedSwingPower;

    private readonly float[] launchModelPowers = new float[] { 0.10f, 0.50f, 1.00f, 1.15f };
    private readonly float[] launchModelSpeeds = new float[] { 17.000f, 85.000f, 170.000f, 195.500f };
    private readonly float launchModelReferenceSrvMul = 2.00f;
    private bool golfBallVelocityReflectionInitialized;
    private Type cachedGolfBallTypeForVelocity;
    private PropertyInfo cachedGolfBallRigidbodyProperty;
    private bool rigidbodyVelocityReflectionInitialized;
    private PropertyInfo cachedRigidbodyLinearVelocityProperty;
    private readonly float trajectoryGravity = 9.81f;

    private GameObject shotPathObject;
    private LineRenderer shotPathLine;
    private Material shotPathMaterial;
    private GameObject predictedPathObject;
    private LineRenderer predictedPathLine;
    private Material predictedPathMaterial;
    private GameObject frozenPredictedPathObject;
    private LineRenderer frozenPredictedPathLine;
    private Material frozenPredictedPathMaterial;
    private readonly List<Vector3> shotPathPoints = new List<Vector3>(768);
    private readonly List<Vector3> predictedPathPoints = new List<Vector3>(384);
    private readonly List<Vector3> frozenPredictedPathPoints = new List<Vector3>(384);
    private bool predictedImpactPreviewValid;
    private Vector3 predictedImpactPreviewPoint = Vector3.zero;
    private Vector3 predictedImpactPreviewApproachDirection = Vector3.forward;
    private bool frozenImpactPreviewValid;
    private Vector3 frozenImpactPreviewPoint = Vector3.zero;
    private Vector3 frozenImpactPreviewApproachDirection = Vector3.forward;
    private bool lockLivePredictedPath;
    private bool observedBallMotionSinceLastShot;
    private bool isRecordingShotPath;
    private float predictedTrajectoryHideStartTime;
    private float nextPredictedPathRefreshTime;
    private Vector3 lastShotPathBallPosition = Vector3.zero;
    private float lastShotPathMoveTime;
    private readonly float predictedUnlockSpeedThreshold = 0.12f;
    private readonly float shotPathHeightOffset = 0.14f;
    private readonly float shotPathMoveThreshold = 0.004f;
    private readonly float shotPathPointSpacing = 0.012f;
    private readonly int shotPathMaxPoints = 3072;
    private readonly float shotPathStationaryDelay = 0.65f;
    private readonly int predictedPathMaxSteps = 360;
    private readonly float predictedPathMaxTime = 7.2f;
    private readonly float predictedPathPointSpacing = 0.30f;
    private readonly float predictedPathRefreshInterval = 0.05f;
    private readonly float predictedTrajectoryUnlockFallbackDelay = 0.75f;
    private bool predictedPathCacheValid;
    private Component cachedPredictedPathBall;
    private Vector3 cachedPredictedShotOrigin = Vector3.zero;
    private Vector3 cachedPredictedAimTargetPosition = Vector3.zero;
    private float cachedPredictedSwingPower;
    private float cachedPredictedSwingPitch;
    private readonly float predictedPathRebuildDistanceEpsilon = 0.015f;
    private readonly float predictedPathRebuildPowerEpsilon = 0.0025f;
    private readonly float predictedPathRebuildPitchEpsilon = 0.05f;

    private readonly string configPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Mods", "SuperHackerGolf.cfg");
    private string assistToggleKeyName = "F";
    private string coffeeBoostKeyName = "F2";
    private string nearestBallModeKeyName = "F3";
    private string unlockAllCosmeticsKeyName = "F4";
    private string assistToggleKeyLabel = "F";
    private string coffeeBoostKeyLabel = "F2";
    private string nearestBallModeKeyLabel = "F3";
    private string unlockAllCosmeticsKeyLabel = "F4";
    private Key assistToggleKey = Key.F;
    private Key coffeeBoostKey = Key.F2;
    private Key nearestBallModeKey = Key.F3;
    private Key unlockAllCosmeticsKey = Key.F4;
    private bool actualTrailEnabled = true;
    private bool predictedTrailEnabled = true;
    private bool frozenTrailEnabled = true;
    private bool impactPreviewEnabled = true;
    private bool allowOvercharge;             // default false: clamp auto-fire at 100% instead of the game's 115% overcharge cap
    private bool instaHitEnabled;             // default false: let the player charge manually, mod only auto-releases at optimal power
    private float windStrength = 0.0041f;     // cross-wind lateral force coefficient — empirically tuned for Dir*Spd source
    private float windDragStrength = 0.04f;   // along-wind drag coefficient — headwinds/tailwinds need ~10x more effect than crosswind drift
    private bool settingsGuiVisible;
    private string settingsGuiKeyName = "F8";
    private string settingsGuiKeyLabel = "F8";
    private Key settingsGuiKey = Key.F8;
    private float impactPreviewTargetFps;
    private int impactPreviewTextureWidth = 640;
    private int impactPreviewTextureHeight = 360;
    private float actualTrailStartWidth = 0.22f;
    private float actualTrailEndWidth = 0.18f;
    private float predictedTrailStartWidth = 0.18f;
    private float predictedTrailEndWidth = 0.14f;
    private float frozenTrailStartWidth = 0.20f;
    private float frozenTrailEndWidth = 0.16f;
    private Color actualTrailColor = new Color(1f, 0.58f, 0.20f, 1f);
    private Color predictedTrailColor = new Color(0.36f, 0.95f, 0.46f, 0.95f);
    private Color frozenTrailColor = new Color(0.36f, 0.74f, 1f, 0.92f);
    private bool visualsInitialized;
    private readonly float visualsInitializationDelay = 2.5f;
    private bool trailVisualSettingsDirty = true;
    private bool actualTrailLineDirty = true;
    private bool predictedTrailLineDirty = true;
    private bool frozenTrailLineDirty = true;
    private bool hudDirty = true;
    private float nextHudRefreshTime;
    private readonly float hudRefreshInterval = 0.1f;
    private string cachedLeftHudText = "";
    private string cachedCenterHudText = "";
    private string cachedRightHudText = "";
    private string cachedBottomHudText = "";
    private bool nearestAnyBallModeEnabled;
    private float nextNearestAnyBallResolveTime;
    private readonly float nearestAnyBallResolveInterval = 0.1f;
    private readonly List<Component> cachedGolfBalls = new List<Component>(64);
    private float nextGolfBallCacheRefreshTime;
    private readonly float golfBallCacheRefreshInterval = 0.75f;
    private readonly float emptyGolfBallCacheRefreshInterval = 2f;
    private float nextImpactPreviewRenderTime;
    private Camera cachedImpactPreviewReferenceCamera;
    private float nextImpactPreviewReferenceCameraRefreshTime;
    private readonly float impactPreviewReferenceCameraRefreshInterval = 1f;
    private readonly float impactPreviewAutoTargetFps = 60f;
    private readonly RaycastHit[] impactPreviewRaycastHits = new RaycastHit[24];
    private readonly RaycastHit[] impactPreviewGroundProbeHits = new RaycastHit[24];
    private readonly object[] cachedSpeedBoostArgs = new object[1];
    private readonly object[] cachedEaseInArgs = new object[1];
    private readonly object[] cachedMatchSetupGetValueArgs = new object[1];
    private readonly object[] cachedChargingStateArgs = new object[1];
    private readonly object[] cachedUpdateSwingPowerArgs = new object[] { true, false };
}
